<!-- \setcounter{page}{1} -->

\cleardoublepage
\pagenumbering{arabic}

# Avant-propos {-}

\adjustmtc
\minitoc

## Pourquoi se former à R
Le logiciel et langage de programmation R s'est imposé comme un outil incontournable d'analyse et de gestion des données scientifiques (et des données d'une manière générale). Il devient indispensable dans ce contexte d'en maîtriser *a minima* les bases. Le succès de R n'est pas un hasard : R est un logiciel que tout le monde peut se procurer librement, et son fonctionnement à base de scripts assure la **transparence** et la **reproductibilité** des résultats scientifiques (sous réserve de respecter quelques règles que nous aborderons dans ce livre). R repose sur une **communauté** très active à l'origine de la création de plusieurs milliers de modules complémentaires (packages) permettant les analyses statistiques les plus pointues. Il est disponible sur les principaux systèmes d'exploitation (Linux, OSX et Windows). Les codes R (ou scripts) sont, sauf cas exceptionnels, indépendants du système d'exploitation utilisé, assurant ainsi leur **portabilité**. R est également un outil qui s'adapte à tous les besoins, depuis de simples statistiques descriptives pour des petits jeux de données jusqu'à la gestion et l'analyse de gros de jeux de données (SIG, génomes, BigData ...), que ce soit en local sur un ordinateur, ou à distance sur des serveurs.

## Les objectifs de l'ouvrage
Ce livre est né de la demande des étudiants et professionnels que j'ai eu la chance de rencontrer et de former à R. Les scientifiques, les étudiants et autres personnes souhaitant s'initier à R y trouveront toutes les ressources nécessaires à la mise en œuvre de leurs propres projets scientifiques et à la valorisation de leurs résultats. Il existe de nombreux livres dédiés à R, mais aucun ne couvre les éléments de base de ce langage qui permettent de rendre des résultats scientifiques publiables et reproductibles. Ainsi, tout au long de cet ouvrage nous nous efforcerons de rédiger non seulement un code fonctionnel pour la machine, mais aussi un code lisible et réutilisable pour les humains.

Tous les codes présentés dans ce livre sont disponibles sur [dunod.com](https://www.dunod.com/). 

## Lectures complémentaires

* "R pour les débutants", Emmanuel Paradis (https://cran.r-project.org/doc/contrib/Paradis-rdebuts_fr.pdf)
* "Introduction à la programmation avec R", Vincent Goulet (https://cran.r-project.org/doc/contrib/Goulet_introduction_programmation_R.pdf)
* Le blog http://rzine.fr, un site collaboratif et interdisciplinaire sur la pratique de R en sciences humaines et sociales

## Remerciements

Je remercie toutes celles et ceux qui ont participé à améliorer ce livre par leurs conseils, leurs suggestions de modifications et leurs corrections (par ordre alphabétique) : Camila BF, Marc G, Susi LH, Emmanuel P, Estefania QH, Baptiste R et Jean-Christophe S.
