# Les fonctions {#fonctions}

## Qu'est-ce qu'une fonction

Avec ce chapitre nous allons avoir un premier apperçu de la puissance de R avec les fonctions. Une fonction est un ensemble de lignes de code permettant d'exécuter une tâche particulière. Nous avons vu de nombreuses fonctions lors des précédents chapitres, la plus simple étant la fonction `+` permettant d'ajouter deux nombres entre eux, ou d'autres plus complexes comme `c()` ou `data.frame()` permettant de créer un `vector` ou un `data.frame`. Dans tous les cas une fonction se reconnait grâce aux parenthèses qui la suive dans laquelle nous allons renseigner des **arguments**. Les arguments correspondent aux informations que nous souhaitons transmettre à notre fonction pour qu'elle exécute la tâche que nous souhaitons réaliser. 

```{block, type='rmdnote'}
Pour les fonctions les plus simples comme `+`, les parenthèses ont été supprimées pour que le code soit plus facile à lire, mais il s'agit bien d'une fonction qui peut s'utiliser avec des parenthèse si nous utilisons le signe `+` entre guillemets.
```

```{r}
5 + 2
'+'(5, 2)
```

Dans ce chapitre nous allons nous focaliser sur les fonctions les plus courantes de façon à ce qu'il soit consultable comme un dictionnaire. Il ne s'agit donc pas de tout apprendre par coeur mais bien de savoir que ces fonctions existent et de pouvoir consulter ce chapitre plus tard comme référence. Avec le temps et la pratique nous finirons par les connaître par coeur ! Il y a plus de 1000 fonctions à ce jour dans la version de base de R, et plus de 10000 packages complémentaires pouvant être installer, chacun contenant plusieurs dizaines de fonctions, alors avant de nous lancer dans l'écriture d'une nouvelle fonction, il faudra toujours vérifier qu'elle n'existe pas déjà.

## Les fonctions les plus courantes

Pour travailler avec es fonctions nous allons utiliser le jeu de données `iris` qui est inclu avec la version de base de R et qui correspond à la longeur et à la largeur des sépales et des pétales de différentes espèces d'iris. Le jeu de données est sous la forme d'un `data.frame` de 5 colonnes et de 150 lignes.

### La fonction indispensable : l'aide de R

help
? => ?base
??

### Visualiser les données

str
head
tail
names
cat
print

### Manipuler les données 

%in%
rank
order
sort
append
cbind
rbind
paste et paste0
rev

### Fonctions mathématiques

exp
sqrt
t
abs
sin
cos
tan
log
log10
acos
asin
atan

### Statistiques descriptives

mean
sd
max
min
quartile
summary
median
length
nrow
ncol
round
ceiling
floor
rowSums
colSums
rowMeans
colMeans
aggregate
range
unique

## Autres fonctions utiles

getwd
setwd
seq_along
:
rep
seq
ls
rm

## Ecrire une fonction

XXX
