# (PART) Scripts utilisés dans le livre {-}

# Premiers pas {#premiersPas}

## Installation de R

## R comme calculatrice

### Les opérateurs arithmétiques

```{r 011-conceptBase-1, eval=FALSE}
5 + 5
```

```{r 011-conceptBase-2, eval=FALSE}
5 + 5 * 2
(5 + 5) * 2
```

```{r 011-conceptBase-3, eval=FALSE}
451 %% 2
288 %% 2
(5 + 5 * 2) %% 2
((5 + 5) * 2) %% 2
```

```{r 011-conceptBase-4, eval=FALSE}
pi
pi * 5^2
1/0
```

### Les opérateurs de comparaison

```{r 011-conceptBase-5, eval=FALSE}
5 > 3 
```

```{r 011-conceptBase-6, eval=FALSE}
5 > 3
2 < 1.5
2 <= 2
3.2 >= 1.5
```

```{r 011-conceptBase-7, eval=FALSE}
(5 + 8) > (3 * 45/2) 
```

```{r 011-conceptBase-8, eval=FALSE}
42 == 53
58 == 58
```

```{r 011-conceptBase-9, eval=FALSE}
42 == 53
42 != 53
(3 + 2) != 5
10/2 == 5
```

```{r 011-conceptBase-10, eval=FALSE}
TRUE == TRUE
TRUE > FALSE
1 == TRUE
0 == FALSE
TRUE + 1
FALSE + 1
(FALSE + 1) == TRUE
```

```{r 011-conceptBase-11, eval=FALSE}
T == TRUE
F == FALSE
T == 1
F == 0
(F + 1) == TRUE
```

```{r 011-conceptBase-11b, eval=FALSE}
print(T)
T <- FALSE
print(T)
```

### Les opérateurs logiques 

```{r 011-conceptBase-12, eval=FALSE}
!TRUE
!FALSE
((3 + 2) == 5) & ((3 + 3) == 5)
((3 + 2) == 5) & ((3 + 3) == 6)
(3 < 5) & (5 < 5)
(3 < 5) & (5 <= 5)
```

```{r 011-conceptBase-13, eval=FALSE}
xor((3 + 2) == 5, (3 + 3) == 6)
xor((3 + 2) == 5, (3 + 2) == 6)
xor((3 + 3) == 5, (3 + 2) == 6)
xor((3 + 3) == 5, (3 + 3) == 6)
```

### Aide sur les opérateurs

## La notion d'objet 

```{r 011-conceptBase-14, eval=FALSE}
nbrRep <- 5
nbrRep = 5
5 -> nbrRep
```

```{r 011-conceptBase-15, eval=FALSE}
nbrRep <- 5
```

```{r 011-conceptBase-16, eval=FALSE}
nbrRep + 2
nbrRep * 5 - 45/56
pi * nbrRep^2
```

```{r 011-conceptBase-17, eval=FALSE}
nbrRep <- 5
nbrRep + 2
nbrRep <- 10
nbrRep + 2
nbrRep <- 5 * 2 + 7/3
nbrRep + 2
```

```{r 011-conceptBase-18, eval=FALSE}
(5 + 9^2 - 1/18) / (32 * 45/8 + 3)
terme01 <- 5 + 9^2 - 1/18
terme02 <- 32 * 45/8 + 3
terme01 / terme02
```

## Les scripts

### Créer un script et le documenter

```{r 011-conceptBase-19, eval=FALSE}
# création objet nombre de répétitions
nbrRep <- 5 # commentaire de fin de ligne
```

```{r 011-conceptBase-20, eval=FALSE}
nbrRep <- 5
# nbrRep + 5
```

```{r 011-conceptBase-21, eval=FALSE}
# ------------------------------------------------------------
# Voici un script pour acquérir les concepts de base 
# avec R
# date de création : 25/06/2018
# auteur : François Rebaudo
# ------------------------------------------------------------

# [1] création de l'objet nombre de répétitions
# ------------------------------------------------------------

nbrRep <- 5

# [2] calculs simples
# ------------------------------------------------------------

pi * nbrRep^2
```

### Exécuter un script

## Conclusion
