---
title: "Se former au logiciel R : initiation et perfectionnement"
author: "François Rebaudo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib]
biblio-style: apalike
#link-citations: yes
#github-repo: https://github.com/frareb/myRBook_FR
#url: 'http://myrbookfr.netlify.com/'
description: "Un guide pour acquérir les bases de la programmation avec R et conduire efficacement la gestion et l'analyse de ses données."
---

# Préambule

Ce livre est incomplet pour le moment et vous visualisez sa version préliminaire. Si vous avez des commentaires, des suggestions ou si vous identifiez des erreurs, n'hésitez pas à m'envoyer un mail (francois.rebaudo@ird.fr), ou si vous connaissez GitHub sur le site du projet (https://github.com/frareb/myRBook_FR). Ce livre est également disponible en espagnol (http://myrbooksp.netlify.com/). 

Dernières modifications:

**13/07/2018**

* mise en ligne du contenu en français sur la base du livre en espagnol
* Les conteneurs de données (partie 3) : les data.frame

# Remerciements {#remerciements}

Je remercie tous les contributeurs qui ont participé à améliorer ce livre par leurs conseils, leurs suggestions de modifications et leurs corrections : 

=> liste à mettre à jour (attente de confirmation écrite des contributeurs)

* Camila Benavides Frias (Bolivia)
* EQ ()

Les versions gitbook, html et epub de ce livre utilisent les icônes open source de Font Awesome (https://fontawesome.com). La version PDF utilise les icônes issues du projet Tango disponibles depuis openclipart (https://openclipart.org/). Ce livre a été écrit avec le package R bookdown (https://bookdown.org/). Le code source est disponible sur GitHub (https://github.com/frareb/myRBook_FR). La compilation utilise Travis CI (https://travis-ci.org). La version en ligne est hébergée et mise à jour grâce à Netlify (http://myrbookfr.netlify.com/).
